// client/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';

	import { logInUser } from '$lib/api/auth';
	import Arrow from '$lib/assets/icons/Arrow.svelte';
	import AuthPage from '$lib/components/layout/AuthPage.svelte';
	import { auth } from '$lib/stores/auth.svelte';
	import { onMount } from 'svelte';

	let email = $state('');
	let password = $state('');
	let error = $state('');
	let isSubmitting = $state(false);

	const handleSubmit = async (event: SubmitEvent) => {
		event.preventDefault();

		error = '';
		isSubmitting = true;

		try {
			await logInUser(email, password);

			await auth.load();

			if (auth.isApproved) {
				await goto(resolve('/'));
				return;
			}

			await goto(resolve('/waiting-room'));
		} catch (err) {
			error = err instanceof Error ? err.message : 'Unable to log in.';
		} finally {
			isSubmitting = false;
		}
	};

	onMount(async () => {
		if (!auth.isAuthenticated) {
			await auth.load();
		}

		if (auth.isAuthenticated) {
			await goto(resolve('/waiting-room'));
		}
	});
</script>

<svelte:head>
	<title>Log In | Bayou Boy Exotics</title>
	<meta name="description" content="Log in to your Bayou Boy Exotics account." />
</svelte:head>

<AuthPage
	image="/images/login.png"
	imageAlt="Bayou Boy white ibis relaxing in the bayou at sunset"
	titleLead="Welcome"
	titleAccent="back."
	description="Log in to access your account."
>
	<form class="space-y-5" onsubmit={handleSubmit}>
		<label class="block">
			<span class="mb-2 block text-xs font-bold tracking-[0.14em] text-accent uppercase">
				Email
			</span>

			<input
				type="email"
				name="email"
				autocomplete="email"
				required
				bind:value={email}
				placeholder="you@email.com"
				class="w-full rounded-vintage border border-border bg-background/30 px-4 py-3.5 text-foreground placeholder:text-muted/50 focus:border-accent focus:ring-accent"
			/>
		</label>

		<label class="block">
			<span class="mb-2 block text-xs font-bold tracking-[0.14em] text-accent uppercase">
				Password
			</span>

			<input
				type="password"
				name="password"
				autocomplete="current-password"
				required
				bind:value={password}
				class="w-full rounded-vintage border border-border bg-background/30 px-4 py-3.5 text-foreground focus:border-accent focus:ring-accent"
			/>
		</label>

		{#if error}
			<p
				role="alert"
				class="rounded-vintage border border-red-500/40 bg-red-950/30 px-4 py-3 text-sm text-red-200"
			>
				{error}
			</p>
		{/if}

		<button
			type="submit"
			disabled={isSubmitting}
			class="group flex w-full items-center justify-center gap-3 rounded-vintage border border-highlight bg-black/70 px-5 py-3.5 font-bold text-accent transition hover:border-accent/80 hover:bg-black/85 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"
		>
			<span>{isSubmitting ? 'Logging In...' : 'Log In'}</span>

			{#if !isSubmitting}
				<Arrow class="size-4 transition-transform group-hover:translate-x-1" />
			{/if}
		</button>

		<div class="flex items-center gap-4 py-1">
			<div class="h-px flex-1 bg-border"></div>
			<span class="text-xs font-semibold text-muted">OR</span>
			<div class="h-px flex-1 bg-border"></div>
		</div>

		<p class="text-center text-sm text-muted">
			Don't have an account?
			<a
				href={resolve('/sign-up')}
				class="ml-1 inline-flex items-center gap-1.5 font-semibold text-accent"
			>
				Sign Up
				<Arrow class="size-3.5" />
			</a>
		</p>

		<button
			type="button"
			class="mx-auto block text-sm text-highlight transition hover:text-foreground"
		>
			Forgot your password?
		</button>
	</form>
</AuthPage>

// admin/src/pages/Login.tsx
import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";

import AdminCard from "../components/ui/AdminCard";
import { useAuth } from "../auth/useAuth";

export default function Login() {
  const auth = useAuth();
  const navigate = useNavigate();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");

  if (auth.isLoading) {
    return null;
  }

  if (auth.isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  const handleSubmit = async (event: React.SyntheticEvent<HTMLFormElement>) => {
    event.preventDefault();

    setError("");
    setIsSubmitting(true);

    try {
      await auth.signIn(email, password);
      navigate("/", { replace: true });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to sign in.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="relative flex min-h-screen items-start justify-start overflow-hidden bg-white px-6 pt-8 md:px-12 md:pt-12">
      <div
        className="
          pointer-events-none
          absolute inset-0
          bg-[url('/images/bb-sketch.png')]
          bg-contain
          bg-bottom-right
          bg-no-repeat
          opacity-10
        "
      />

      <div className="relative z-10 w-full max-w-md">
        <AdminCard className="bg-white/95 shadow-[0_22px_60px_-14px_rgba(43,84,126,0.7)]">
          <p className="admin-eyebrow">Team Bayou</p>

          <h1 className="mt-2 text-3xl">Welcome back.</h1>

          <p className="mt-2 text-sm text-muted">
            Sign in to manage Bayou Boy Exotics.
          </p>

          <form onSubmit={handleSubmit} className="mt-8 space-y-5">
            <div className="admin-field">
              <label htmlFor="email" className="admin-label">
                Email
              </label>

              <input
                id="email"
                type="email"
                autoComplete="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                className="admin-input"
                placeholder="you@bayouboy.com"
                required
              />
            </div>

            <div className="admin-field">
              <label htmlFor="password" className="admin-label">
                Password
              </label>

              <input
                id="password"
                type="password"
                autoComplete="current-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                className="admin-input"
                required
              />
            </div>

            {error && <p className="admin-error-text">{error}</p>}

            <button
              type="submit"
              disabled={isSubmitting}
              className="admin-button-primary w-full disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isSubmitting ? "Signing in..." : "Sign In"}
            </button>
          </form>
        </AdminCard>
      </div>
    </div>
  );
}
